### ISSUE TITLE
SILO input transformer

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS-SILO#644]
Integrate and finalize the SILO input transformer. 

It is a follow up to https://github.com/GenSpectrum/LAPIS-SILO/issues/562. This issue removes the TSV/FASTA input format from the SILO code (and leaves SILO only with the NDJSON input). The SILO input is a separate tool that can translate the TSV/FASTA format to the NDJSON input, so that SILO still "supports" both formats (eventually by running the input transformer first).

This is a list of tasks that need to be done (not necessarily in a good order for implementation):
- [ ] SILO input transformer: Integrate the code into the SILO repository.
  - Currently it's in this private repo: https://github.com/fengelniederhammer/SILO-input-transformer
- [ ] SILO input transformer: add logging
- [ ] SILO input transformer: Allow compressed input files
- [ ] SILO input transformer: compress sequences in intermediate steps
  - to reduce the amount of data that needs to be transferred between the program and the disc.
- [ ] SILO input transformer: allow command line arguments
  - especially specifying where the config is located and whether to keep intermediate files (and maybe the log level)
- [ ] SILO input transformer: error messages
  - We already have error handling, but the errors might be hard to understand for users.
- [ ] SILO input transformer: add more unit tests
- [ ] SILO input transformer: add some e2e tests
- [ ] SILO input transformer: parallelize where possible
- [ ] SILO input transformer: support SAM files
- [ ] SILO input transformer: include insertions
  - to do: think about whether we want to keep the old input format
- [ ] SILO input transformer: clean up temp folders
